source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Flower_Example', :exclusive => true do
  pod "Flower", :path => "../"
end

target 'Flower_Tests', :exclusive => true do
  pod "Flower", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
